### ISSUE TITLE
Newline deletion

### ISSUE THREAD

**Issue by 0xZunia** [AdrianWeaver/codingame_makefile#1]
Tous les fichiers .cpp et .hpp doivent finir avec un newline supplémentaire, car lors de la compilation, la dernière ligne de chaque fichier est supprimée.

**Comment by AdrianWeaver** [comment]
Merci d'avoir remarqué ça.
Effectivement je vais essayer à l'avenir de proposer un quickfix pour ça.
Ou à défaut préciser que les fichiers doivent toujours se terminer par un newline.
